name: Deploy to S3

on:
  push:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1  # Middle East (UAE)
        
    - name: Deploy to S3
      run: |
        aws s3 sync out/ s3://www.tekamul.link --delete
        
    - name: Set website configuration
      run: |
        cat > website-config.json << 'EOF'
        {
          "IndexDocument": {
            "Suffix": "index.html"
          },
          "ErrorDocument": {
            "Key": "en/index.html"
          },
          "RoutingRules": [
            {
              "Condition": {
                "KeyPrefixEquals": "en/",
                "HttpErrorCodeReturnedEquals": "404"
              },
              "Redirect": {
                "ReplaceKeyWith": "en/index.html"
              }
            },
            {
              "Condition": {
                "KeyPrefixEquals": "ar/",
                "HttpErrorCodeReturnedEquals": "404"
              },
              "Redirect": {
                "ReplaceKeyWith": "ar/index.html"
              }
            },
            {
              "Condition": {
                "HttpErrorCodeReturnedEquals": "404"
              },
              "Redirect": {
                "ReplaceKeyWith": "en/index.html"
              }
            }
          ]
        }
        EOF
        aws s3api put-bucket-website --bucket www.tekamul.link --website-configuration file://website-config.json